name: Main CI/CD

on:
  push:
    branches: [ dev ]
    paths:
      - 'react-app/**'
      - '.github/**'

jobs:

jobs:
  call-workflow-nodejs:
    uses: ./.github/workflows/node.js.yml

  call-workflow-s3-sync:
    needs: call-workflow-nodejs
    uses: ./.github/workflows/s3-sync.yml
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      region: ${{ secrets.AWS_REGION }}
      bucket_name: ${{ secrets.AWS_S3_BUCKET_NAME }}
