name: Pulumi Workflow
on:
  push:
    branches: [ dev ]
    paths:
      - 'infra/**'
      - '.github/workflows/pulumi.yml'
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/echo/
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: echo $(pwd) && echo $stack_env
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        if: github.event_name == 'pull_request'
        with:
          max-line-length: "100"
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.stack_env }}
          work-dir: ./infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PULUMI }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PULUMI }}
          AWS_REGION: ${{ secrets.AWS_REGION }}